Repository MannLabs/alphadia, pull requests merged in 2025-03, with the labels that each got.

#495 Update prediction config to use enabled pattern
  alphadia/constants/default.yaml
  alphadia/search_plan.py
  alphadia/search_step.py
  gui/workflows/PeptideCentric.v1.json
  tests/e2e_tests/e2e_test_cases.yaml
  tests/unit_tests/test_search_plan.py
  tests/unit_tests/test_search_step.py
Labels: test:e2e, breaking-change

#499 Small tweaks
  .github/workflows/publish_docker_image.yml
  README.md
  alphadia/exceptions.py
  alphadia/workflow/config.py
  alphadia/workflow/reporting.py
  docs/installation.md
  gui/src/renderer/components/ExecutionEngine.js
Labels: code-review

#510 fix wrong config key
  alphadia/outputtransform.py
Labels: bug
