Repository MannLabs/alphadia, pull requests merged in 2025-04, with the labels that each got.

#518 add SLURM_JOB_ID logging to environment info
  alphadia/utilities/logging.py
Labels: code-review

#520 Don't perform FASTA reannotation in MBR step
  alphadia/constants/multistep.yaml
Labels: bug

#542 Slimmer utils
  alphadia/utils.py
  docs/methods.md
Labels: test:e2e

#521 Improve config handling
  alphadia/cli.py
  alphadia/search_step.py
  docs/developer_guide.md
  docs/methods/command-line.md
  tests/unit_tests/test_cli.py
Labels: code-review
